# fundo do ecrã
rootcolor=101417ff

# janelas inativas
bordercolor=41474dff

# focused
focuscolor=004b70ff

maxmizescreencolor=b8c8d9ff

urgentcolor=ffb4abff

scratchpadcolor=d0c0e8ff

globalcolor=394956ff

overlaycolor=4d4162ff
