windowrule=isfloating:1,appid:musicpresence
windowrule=isfloating:1,appid:feh

windowrule=focused_opacity:0.7,appid:(firefox|spotify|steam|thunar|net.lutris.Lutris|org.prismlauncher.PrismLauncher)
windowrule=unfocused_opacity:0.7,appid:(firefox|spotify|steam|thunar|net.lutris.Lutris|org.prismlauncher.PrismLauncher)

windowrule = appid:feh, size 60%
windowrule=width:1000,height:900,appid:feh

